import T from"./vendor/swiper-bundle.mjs";const A=(()=>{const L='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M6.4 5L5 6.4L10.6 12L5 17.6L6.4 19L12 13.4L17.6 19L19 17.6L13.4 12L19 6.4L17.6 5L12 10.6z"/></svg>',w='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M14.7 6.3a1 1 0 0 1 0 1.4L10.4 12l4.3 4.3a1 1 0 1 1-1.4 1.4l-5-5a1 1 0 0 1 0-1.4l5-5a1 1 0 0 1 1.4 0z"/></svg>',E='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M9.3 6.3a1 1 0 0 0 0 1.4L13.6 12l-4.3 4.3a1 1 0 1 0 1.4 1.4l5-5a1 1 0 0 0 0-1.4l-5-5a1 1 0 0 0-1.4 0z"/></svg>',h='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 3a1 1 0 0 1 1 1v9.58l3.3-3.3a1 1 0 1 1 1.4 1.42l-5 5a1 1 0 0 1-1.4 0l-5-5a1 1 0 1 1 1.4-1.42l3.3 3.3V4a1 1 0 0 1 1-1ZM4 19a1 1 0 0 1 1-1h14a1 1 0 1 1 0 2H5a1 1 0 0 1-1-1Z"/></svg>',f=['[class^="related-"]','[class*=" related-"]'].join(",");let n=null,d=null,g=null,l=null,i=null;function m(e){return String(e).replace(/[&<>"']/g,t=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[t])}function C(){const e=document.createElement("div");return e.className="image-gallery",e.setAttribute("role","dialog"),e.setAttribute("aria-modal","true"),e.setAttribute("aria-hidden","true"),e.innerHTML=`
            <div class="image-gallery__backdrop" data-gallery-close></div>
            <div class="image-gallery__counter" aria-live="polite"></div>
            <button type="button" class="image-gallery__btn image-gallery__download" data-gallery-download aria-label="T\u1EA3i \u1EA3nh">${h}</button>
            <button type="button" class="image-gallery__btn image-gallery__close" data-gallery-close aria-label="\u0110\xF3ng">${L}</button>
            <button type="button" class="image-gallery__btn image-gallery__nav image-gallery__nav--prev" aria-label="\u1EA2nh tr\u01B0\u1EDBc">${w}</button>
            <button type="button" class="image-gallery__btn image-gallery__nav image-gallery__nav--next" aria-label="\u1EA2nh sau">${E}</button>
            <div class="swiper image-gallery__swiper">
                <div class="swiper-wrapper"></div>
            </div>
        `,d=e.querySelector(".image-gallery__counter"),g=e.querySelector(".image-gallery__swiper"),e.addEventListener("click",t=>{if(t.target.closest("[data-gallery-close]"))return c();if(t.target.closest("[data-gallery-download]"))return $();t.target.closest(".image-gallery__btn")||t.target.closest(".image-gallery__img")||c()}),document.body.appendChild(e),e}function S(e){return!!(e.offsetWidth||e.offsetHeight||e.getClientRects().length)}function x(e){return!!f&&!!e.closest(f)}function p(){const e=document.getElementById("content");return e?Array.from(e.querySelectorAll("img")).filter(t=>S(t)&&!x(t)):[]}function O(e){const t=e.closest("figure"),a=t?t.querySelector("figcaption"):null;return(a?a.textContent.trim():"")||(e.alt||"").trim()}function I(e){const t=g.querySelector(".swiper-wrapper");t.innerHTML=e.map(a=>{const r=a.currentSrc||a.src,o=m(a.alt||""),u=m(O(a));return`
                    <div class="swiper-slide">
                        <figure class="image-gallery__figure">
                            <img class="image-gallery__img" src="${r}" alt="${o}">
                            ${u?`<figcaption class="image-gallery__caption">${u}</figcaption>`:""}
                        </figure>
                    </div>
                `}).join("")}function y(e,t){d&&(d.textContent=`${e+1} / ${t}`),n&&(n.dataset.single=t<=1?"true":"false")}function k(e){return new T(g,{initialSlide:e,speed:400,spaceBetween:40,slidesPerView:1,keyboard:{enabled:!0,onlyInViewport:!1},navigation:{prevEl:n.querySelector(".image-gallery__nav--prev"),nextEl:n.querySelector(".image-gallery__nav--next")},on:{init(t){y(t.activeIndex,t.slides.length)},slideChange(t){y(t.activeIndex,t.slides.length)}}})}function v(e){n||(n=C());const t=p();!t.length||e<0||e>=t.length||(I(t),l&&(l.destroy(!0,!0),l=null),l=k(e),i=document.activeElement,n.classList.add("is-active"),n.setAttribute("aria-hidden","false"),document.body.classList.add("overlay-open"))}function c(){if(!(!n||!n.classList.contains("is-active"))){if(n.classList.remove("is-active"),n.setAttribute("aria-hidden","true"),document.body.classList.remove("overlay-open"),l){const e=l;l=null,setTimeout(()=>e.destroy(!0,!0),300)}i&&typeof i.focus=="function"&&i.focus(),i=null}}async function $(){if(!l)return;const t=l.slides[l.activeIndex]?.querySelector("img");if(!t)return;const a=t.src,r=(a.split("/").pop()||"image").split("?")[0]||"image";try{const o=await fetch(a,{mode:"cors"});if(!o.ok)throw new Error(`status ${o.status}`);const u=await o.blob(),b=URL.createObjectURL(u),s=document.createElement("a");s.href=b,s.download=r,document.body.appendChild(s),s.click(),s.remove(),setTimeout(()=>URL.revokeObjectURL(b),1e3)}catch{window.open(a,"_blank","noopener")}}function R(){return!!n&&n.classList.contains("is-active")}function q(e){const t=e.target.closest("img");if(!t)return;const r=p().indexOf(t);r!==-1&&(e.preventDefault(),v(r))}function _(){const e=document.getElementById("content");e&&(e.addEventListener("click",q),document.addEventListener("keydown",t=>{R()&&t.key==="Escape"&&(t.preventDefault(),c())}))}return document.readyState==="loading"?document.addEventListener("DOMContentLoaded",_):_(),{open:v,close:c}})();export default A;
