import T from"./vendor/swiper-bundle.mjs";const q=(()=>{const w='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M6.4 5L5 6.4L10.6 12L5 17.6L6.4 19L12 13.4L17.6 19L19 17.6L13.4 12L19 6.4L17.6 5L12 10.6z"/></svg>',h='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M14.7 6.3a1 1 0 0 1 0 1.4L10.4 12l4.3 4.3a1 1 0 1 1-1.4 1.4l-5-5a1 1 0 0 1 0-1.4l5-5a1 1 0 0 1 1.4 0z"/></svg>',E='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M9.3 6.3a1 1 0 0 0 0 1.4L13.6 12l-4.3 4.3a1 1 0 1 0 1.4 1.4l5-5a1 1 0 0 0 0-1.4l-5-5a1 1 0 0 0-1.4 0z"/></svg>',C='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 3a1 1 0 0 1 1 1v9.58l3.3-3.3a1 1 0 1 1 1.4 1.42l-5 5a1 1 0 0 1-1.4 0l-5-5a1 1 0 1 1 1.4-1.42l3.3 3.3V4a1 1 0 0 1 1-1ZM4 19a1 1 0 0 1 1-1h14a1 1 0 1 1 0 2H5a1 1 0 0 1-1-1Z"/></svg>',m=['[class^="related-"]','[class*=" related-"]'].join(","),S=3;let n=null,g=null,f=null,l=null,i=null;function p(e){return String(e).replace(/[&<>"']/g,t=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[t])}function O(){const e=document.createElement("div");return e.className="image-gallery",e.setAttribute("role","dialog"),e.setAttribute("aria-modal","true"),e.setAttribute("aria-hidden","true"),e.innerHTML=`
            <div class="image-gallery__backdrop" data-gallery-close></div>
            <div class="image-gallery__counter" aria-live="polite"></div>
            <button type="button" class="image-gallery__btn image-gallery__download" data-gallery-download aria-label="T\u1EA3i \u1EA3nh">${C}</button>
            <button type="button" class="image-gallery__btn image-gallery__close" data-gallery-close aria-label="\u0110\xF3ng">${w}</button>
            <button type="button" class="image-gallery__btn image-gallery__nav image-gallery__nav--prev" aria-label="\u1EA2nh tr\u01B0\u1EDBc">${h}</button>
            <button type="button" class="image-gallery__btn image-gallery__nav image-gallery__nav--next" aria-label="\u1EA2nh sau">${E}</button>
            <div class="swiper image-gallery__swiper">
                <div class="swiper-wrapper"></div>
            </div>
        `,g=e.querySelector(".image-gallery__counter"),f=e.querySelector(".image-gallery__swiper"),e.addEventListener("click",t=>{if(t.target.closest("[data-gallery-close]"))return u();if(t.target.closest("[data-gallery-download]"))return $();t.target.closest(".image-gallery__btn")||t.target.closest(".image-gallery__zoom")||t.target.closest(".image-gallery__img")||u()}),document.body.appendChild(e),e}function x(e){return!!(e.offsetWidth||e.offsetHeight||e.getClientRects().length)}function I(e){return!!m&&!!e.closest(m)}function y(){const e=document.getElementById("content");return e?Array.from(e.querySelectorAll("img")).filter(t=>x(t)&&!I(t)):[]}function R(e){const t=e.closest("figure"),a=t?t.querySelector("figcaption"):null;return(a?a.textContent.trim():"")||(e.alt||"").trim()}function k(e){const t=f.querySelector(".swiper-wrapper");t.innerHTML=e.map(a=>{const r=a.currentSrc||a.src,o=p(a.alt||""),d=p(R(a));return`
                    <div class="swiper-slide">
                        <figure class="image-gallery__figure">
                            <div class="swiper-zoom-container image-gallery__zoom">
                                <img class="image-gallery__img" src="${r}" alt="${o}">
                            </div>
                            ${d?`<figcaption class="image-gallery__caption">${d}</figcaption>`:""}
                        </figure>
                    </div>
                `}).join("")}function _(e,t){g&&(g.textContent=`${e+1} / ${t}`),n&&(n.dataset.single=t<=1?"true":"false")}function c(e){n&&(n.dataset.zoomed=e?"true":"false")}function z(e){return new T(f,{initialSlide:e,speed:400,spaceBetween:40,slidesPerView:1,keyboard:{enabled:!0,onlyInViewport:!1},zoom:{enabled:!0,minRatio:1,maxRatio:S,toggle:!0},navigation:{prevEl:n.querySelector(".image-gallery__nav--prev"),nextEl:n.querySelector(".image-gallery__nav--next")},on:{init(t){_(t.activeIndex,t.slides.length),c(!1)},slideChange(t){_(t.activeIndex,t.slides.length),c(!1)},zoomChange(t,a){c(a>1)}}})}function v(e){n||(n=O());const t=y();!t.length||e<0||e>=t.length||(k(t),l&&(l.destroy(!0,!0),l=null),l=z(e),i=document.activeElement,n.classList.add("is-active"),n.setAttribute("aria-hidden","false"),document.body.classList.add("overlay-open"))}function u(){if(!(!n||!n.classList.contains("is-active"))){if(l&&l.zoom)try{l.zoom.out()}catch{}if(c(!1),n.classList.remove("is-active"),n.setAttribute("aria-hidden","true"),document.body.classList.remove("overlay-open"),l){const e=l;l=null,setTimeout(()=>e.destroy(!0,!0),300)}i&&typeof i.focus=="function"&&i.focus(),i=null}}async function $(){if(!l)return;const t=l.slides[l.activeIndex]?.querySelector("img");if(!t)return;const a=t.src,r=(a.split("/").pop()||"image").split("?")[0]||"image";try{const o=await fetch(a,{mode:"cors"});if(!o.ok)throw new Error(`status ${o.status}`);const d=await o.blob(),L=URL.createObjectURL(d),s=document.createElement("a");s.href=L,s.download=r,document.body.appendChild(s),s.click(),s.remove(),setTimeout(()=>URL.revokeObjectURL(L),1e3)}catch{window.open(a,"_blank","noopener")}}function A(){return!!n&&n.classList.contains("is-active")}function M(e){const t=e.target.closest("img");if(!t)return;const r=y().indexOf(t);r!==-1&&(e.preventDefault(),v(r))}function b(){const e=document.getElementById("content");e&&(e.addEventListener("click",M),document.addEventListener("keydown",t=>{A()&&t.key==="Escape"&&(t.preventDefault(),u())}))}return document.readyState==="loading"?document.addEventListener("DOMContentLoaded",b):b(),{open:v,close:u}})();export default q;
