(function(){const h="https://r2-thainguyen.media-soft.cloud/common/assets/img_tv1.jpg",g={1:{name:"TNTV",stream:"https://streaming.thainguyentv.vn/hls/livestream.m3u8",poster:h},2:{name:"TNRADIO",stream:"https://radio.thainguyentv.vn/hls/livestream.m3u8",poster:h}},L=(t,e)=>`https://streaming.thainguyentv.vn/apicenter@/scheduler_data&tpl_gui=tpl_tv_scheduler_file_1&channel=${t}&day=${e}`,p=["t:bg-[#30A14A]","t:border-white","t:hover:bg-[#268D3F]"],b=["t:bg-white","t:border-white/20","t:hover:bg-[#F7F7F7]"];let l=null,a=null,d=!1,m=null;const i=()=>document.getElementById("tv-player"),u=()=>document.getElementById("tv-schedule-list");function E(){const t=new Date,e=String(t.getMonth()+1).padStart(2,"0"),n=String(t.getDate()).padStart(2,"0");return`${t.getFullYear()}-${e}-${n}`}function x(){const t=new Date;return t.getHours()*60+t.getMinutes()}function A(t){const e=t.trim().match(/^(\d{1,2}):(\d{2})$/);if(!e)return null;const n=Number(e[1]),r=Number(e[2]);return{label:`${String(n).padStart(2,"0")}:${e[2]}`,minutes:n*60+r}}function v(){a&&(a.destroy(),a=null);const t=i();t&&(t.pause(),t.removeAttribute("src"),t.load()),d=!1}const T="https://cdn.jsdelivr.net/npm/hls.js@1/dist/hls.min.js";function F(){return window.Hls?Promise.resolve():m||(m=new Promise(t=>{const e=document.createElement("script");e.src=T,e.onload=()=>t(),e.onerror=()=>t(),document.head.appendChild(e)}),m)}function $(){const t=i(),e=g[l];if(!t||!e)return;const n=l;if(t.canPlayType("application/vnd.apple.mpegurl")){t.src=e.stream;return}F().then(()=>{if(n!==l)return;const r=window.Hls;!r||!r.isSupported()||(a=new r({autoStartLoad:!1}),a.loadSource(e.stream),a.attachMedia(t),a.on(r.Events.ERROR,(s,o)=>{o.fatal&&v()}),d&&(a.startLoad(),t.play().catch(()=>{})))})}function H(){d||(d=!0,a&&a.startLoad(),i()?.play().catch(()=>{}))}function N(){const t=i();t&&t.addEventListener("play",H)}function f(t){const e=u();e&&(e.innerHTML=`<div class="!roboto t:px-3 t:py-4 t:text-sm t:text-[#8A94A6]">${t}</div>`)}async function _(t){if(u()){f("\u0110ang t\u1EA3i l\u1ECBch ph\xE1t s\xF3ng...");try{const n=await fetch(L(t,E()));if(!n.ok)throw new Error(`HTTP ${n.status}`);const r=await n.text(),s=C(r);if(t!==l)return;if(!s.length){f("Ch\u01B0a c\xF3 l\u1ECBch ph\xE1t s\xF3ng.");return}I(s),y()}catch(n){if(t!==l)return;console.error("[truyen_hinh] schedule fetch failed:",n),f("Kh\xF4ng t\u1EA3i \u0111\u01B0\u1EE3c l\u1ECBch ph\xE1t s\xF3ng.")}}}function C(t){const e=new DOMParser().parseFromString(t,"text/html"),n=[];return e.querySelectorAll("tr.t-r").forEach(r=>{const s=r.querySelectorAll("td");if(s.length<2)return;const o=A(s[0].textContent||""),c=(s[1].textContent||"").trim().replace(/\s+/g," ");!o||!c||n.push({...o,name:c})}),n}function I(t){const e=u();e&&(e.innerHTML=t.map((n,r)=>`
        <a
            href=""
            data-idx="${r}"
            data-minutes="${n.minutes}"
            class="t:flex t:items-start t:gap-x-2 t:px-3 t:py-2 t:rounded-lg t:bg-white t:hover:bg-[#F7F7F7]"
        >
            <span class="!roboto t:text-sm t:text-[#212636] t:shrink-0 t:w-[70px]">${n.label}</span>
            <span class="!roboto t:flex-1 t:min-w-0 t:text-sm t:text-[#212636] t:tracking-[0.15px]">${D(n.name)}</span>
        </a>`).join(""))}function D(t){return t.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}const P=["t:bg-[#DFFFE6]","t:font-bold","t:hover:bg-[#CFF6DA]"];function y(){const t=u();if(!t)return;const e=Array.from(t.querySelectorAll("a[data-minutes]"));if(!e.length)return;const n=x();let r=-1;e.forEach((s,o)=>{Number(s.dataset.minutes)<=n&&(r=o)}),r===-1&&(r=0),e.forEach((s,o)=>{const c=o===r;s.classList.toggle("t:bg-white",!c),P.forEach(R=>s.classList.toggle(R,c)),c?s.setAttribute("aria-current","true"):s.removeAttribute("aria-current")}),e[r].scrollIntoView({block:"nearest"})}function M(t,e){t.classList.remove(...e?b:p),t.classList.add(...e?p:b);const n=t.querySelector("span.noto");n&&(n.classList.toggle("t:text-white",e),n.classList.toggle("t:text-[#212636]",!e));const r=t.querySelectorAll("span.t\\:relative > span");r.length>=2&&(r[0].className=`t:absolute t:size-5 t:rounded-full ${e?"t:bg-white/40":"t:bg-[#F04438]/20"}`,r[1].className=`t:absolute t:size-3.5 t:rounded-full ${e?"t:bg-white/50":"t:bg-[#F04438]/20"}`)}function S(t){if(t===l)return;l=t,document.querySelectorAll("[data-tv-tab]").forEach(n=>{M(n,Number(n.dataset.tvTab)===t)}),v();const e=i();e&&(e.poster=g[t].poster),$(),_(t)}function q(){document.querySelectorAll("[data-tv-tab]").forEach(t=>{t.addEventListener("click",e=>{e.preventDefault(),S(Number(t.dataset.tvTab))})})}function w(){!i()||!u()||(N(),q(),S(1),setInterval(y,60*1e3))}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",w):w()})();
